# Don't print a new line at the start of the prompt
add_newline = true
# Wait 10 milliseconds for starship to check files under the current directory.
scan_timeout = 10
prompt_order = [
    "directory",
    "git_branch",
    "git_commit",
    "git_state",
    "git_status",
    "kubernetes",
    "custom.fairwinds",
    "line_break",
    "character",
]

[directory]
#truncation_length = 4
truncate_to_repo = false

[kubernetes]
style = "green"
disabled = false

[custom.fairwinds]
symbol = "🚀 "
command = "echo $PROJECT:$INVENTORY"
when = """ test "$INVENTORY" != "" """
prefix = " "
style = "bold red"

